language: generic

matrix:
    include:
            - os: linux
              sudo: required
            - os: osx


install:
        - pip install pandas
        - pip install numpy


before_script:
        - wget http://rapid-hub.org/data/angles_UCI_CS.csv
        - wget http://rapid-hub.org/data/angles_UCI_CS_out.csv
script:
       - sh tst/test_repr.sh
