language: generic

matrix:
    include:
            - os: linux
              sudo: required
            - os: osx
   

# This is for Linux and OSX

before_install:
     #Linux
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
     then apt-get --version ; fi
     #Get Version
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; 
     then sudo apt-get install -y $(grep -vE '(^#|^$)' requirements.apt) ; fi
     #Get requirements from requirements.apt for linux

     #osx
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3 ; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then virtualenv venv -p python3; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then source venv/bin/activate; fi

install:
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
          then sudo pip install -r requirements.pip ; fi

        - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip install -r requirements.pip ; fi




before_script:
        - wget http://rapid-hub.org/data/angles_UCI_CS.csv
        - wget http://rapid-hub.org/data/angles_UCI_CS_out.csv
script:
       - sh tst/test_repr.sh
