language: generic

matrix:
    include:
            - os: linux
              sudo: required
            - os: osx
# This is for Linux and OSX

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get --version ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y $(grep -v -E requirements.apt) ; fi

install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install -r requirements.pip ; fi


before_script:
        - wget http://rapid-hub.org/data/angles_UCI_CS.csv
        - wget http://rapid-hub.org/data/angles_UCI_CS_out.csv
script:
       - sh tst/test_repr.sh
