language: python
python:
        - 3.6

install:
        - pip install pandas
        - pip install numpy


before_script:
        - wget http://rapid-hub.org/data/angles_UCI_CS.csv
        - wget http://rapid-hub.org/data/angles_UCI_CS_out.csv
script:
        ./tst/test_repr.sh
