version: 1.0.{build}

build: false

environment:
  matrix:
       - PYTHON: "C:\\Python34"
         PYTHON_VERSION: "3.4.1"
         PYTHON_ARCH: "32"


install:
  - "%PYTHON%/Scripts/pip.exe install pandas"
  - "%PYTHON%/Scripts/pip.exe install numpy"
 
test_script:
  - ps: sh tst/tst_repr.sh


