environment:
  matrix:
       - PYTHON: "C:\\Python36"
         PYTHON_VERSION: 3.6
         PYTHON_ARCH: 64


before_install:
        - pip install pandas
        - pip install numpy

before_script:
        - wget http://rapid-hub.org/data/angles_UCI_CS.csv
        - wget http://rapid-hub.org/data/angles_UCI_CS.out.csv
 
test_script:
        python tst/tst_comp_csv.py


