environment:
  matrix:
       - PYTHON: "C:\\Python36"
         PYTHON_VERSION: 3.6
         PYTHON_ARCH: 64


install:
  - ps: choco install (get-content requirements.win)
  - ps: pip install -r requirements.pip
 
test_script:
  - ps: sh tst/tst_repr.sh


